---
title: "Story"
author: "Emma Caetano"
---

Once upon a time, there was an 8-year-old girl who picked up a bat and was handed a softball. Every day, she went out to the field and practiced with her teammates. She was always working hard and preparing for the games to be played. She always wanted to hit homeruns like the girls she saw on TV. Then one day she realized years of hard work have paid off and passed, and she got the opportunity to play softball in college. She started to research the on-base plus slugging for NCAA softball players and saw that in 2021 there was an average of 3.61 homeruns per player, but in 2022 homeruns became more frequent with 4.06 homeruns. Since this has been her dream since a little girl, she knew she needed to study the data to see how to be the best hitter. She watched swings from 2022 since the OPS was higher and began to analyze and study NCAA softball players swings. Because of this being her overall goal, she packed her bags and moved to Sarasota, with nothing but a bat and glove, leaving everything she knew behind. She was scared and hesitant. Until finally, she moved into her dorm and met the best roommates of all time. She shared how the OPS went up in 2022 and showed them the game film and the OPS percentage contributed to how they play now. They do everything together, play softball together, love each other dearly, and it all ended happily ever after.
